common:
  msg_source: 3                                         #0: not use Lidar
                                                 #1: packet message comes from online Lidar
                                                        #2: packet message comes from ROS or ROS2
                                                        #3: packet message comes from Pcap file
  send_packet_ros: false                                #true: Send packets through ROS or ROS2(Used to record packet)
  send_point_cloud_ros: true                            #true: Send point cloud through ROS or ROS2
lidar:
  - driver:
      lidar_type: RSAIRY             #LiDAR type - RS16, RS32, RSBP, RSHELIOS, RSHELIOS_16P, RS128, RS80, RS48, RSP128, RSP80, RSP48, 
                                   #             RSM1, RSM1_JUMBO, RSM2, RSM3, RSE1, RSMX.
      msop_port: 6699             #Msop port of lidar
      difop_port: 7788             #Difop port of lidar
      imu_port: 6688             #Imu port of lidar
      start_angle: 0               #Start angle of point cloud
      end_angle: 360               #End angle of point cloud 
      wait_for_difop: true
      min_distance: 0.2            #Minimum distance of point cloud
      max_distance: 200            #Maximum distance of point cloud
      use_lidar_clock: true       #true--Use the lidar clock as the message timestamp
                                   #false-- Use the system clock as the timestamp
      dense_points: false          #true: discard NAN points; false: reserve NAN points
      ts_first_point: true        #true: time-stamp point cloud with the first point; false: with the last point;   
      user_layer_bytes: 0          #Bytes of user layer. thers is no user layer if it is 0         
      pcap_repeat: false            #true: The pcap bag will repeat play   

      host_address: "0.0.0.0"      #Address of host
      group_address: "0.0.0.0"     # Address of multicast group   

      #rsview_TwoWvs \ airy_yijia02
    ros:
      ros_frame_id: rslidar                           #Frame id of packet message and point cloud message
      ros_recv_packet_topic: /rslidar_packets          #Topic used to receive lidar packets from ROS
      ros_send_packet_topic: /rslidar_packets          #Topic used to send lidar packets through ROS
      ros_send_imu_data_topic: /rslidar_imu_data         #Topic used to send imu data through ROS
      ros_send_point_cloud_topic: /rslidar_points      #Topic used to send point cloud through ROS
